cmake_minimum_required(VERSION 3.15)
project(mik64_blog_builder)
if(NOT TARGET mik64_blog_builder)
    add_subdirectory(lib/cpp-logger)
    file(GLOB PARSER_SOURCES "cpp/*.cpp")
    add_library(mik64_blog_builder STATIC ${PARSER_SOURCES})
    add_library(mik64::blog-builder ALIAS mik64_blog_builder)
    target_include_directories(mik64_blog_builder PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/h)
    target_compile_features(mik64_blog_builder PRIVATE cxx_std_17)

    target_link_libraries(mik64_blog_builder PRIVATE mik64::cpp-logger)
endif()
add_executable(mik64_blog_builder_test main.cpp)
target_link_libraries(mik64_blog_builder_test PRIVATE mik64::blog-builder)