# blog
blog_title=64mik tech blog
blog_version=v0.1.1
blog_author=64mik

# metaData
page_title=untitled
page_date=untracked
page_lore=none
page_path=untracked
isPost=true

del_start={{
del_end=}}


# builder
start_marker=<=
data_marker=::
end_marker==>
meta_marker=:

# path
templates_file=.\\templates.conf
base_path=.\\src\\base\\base.html