box=<div class="box">|</div>
code-box=<div class="code-box">|</div>
quote = <blockquote>|</blockquote>
hr=<hr>| 
title=<h1 class="title">|</h1>
p=<p>|</p>
bold=<h5 class="bold">|</h5>
tags=<ul class="tag">|</ul>
tag=<li><a href="{{data}}">|</a></li>
img=<img src ="{{data}}">|
link=<a class ="link" href="{{data}}">|</a>
none=| 