box=<div class="box">|</div>
codebox=<div class="codebox">|</div>
hr=<hr>| 
title=<h2 class="title">|</h2>
p=<p>|</p>
bold=<h5 class="bold">|</h5>
list=<ul>|</ul>
li=<li>|</li>
img=<img src ="{{data}}">|
link=<a class ="link" href="{{data}}">|</a>
none=| 